spring:
  profiles:
    active: local

weather:
  services:
    weatherstack:
      label: Weatherstack
      base-url: http://api.weatherstack.com
      api-key: <secret>
    openweathermap:
      label: Open weather map
      base-url: http://api.openweathermap.org
      api-key: <secret>